services:
    app.exception_subscriber:
        class: AppBundle\EventSubscriber\ExceptionListener
        arguments:
            - '@jms_serializer'
        tags:
            - { name: kernel.event_subscriber }

    app.normalizer.resource_validation_exception:
        class: AppBundle\Normalizer\NotFoundHttpExceptionNormalizer
        arguments:
            - { type: 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'  }
        tags:
            - { name: app.normalizer }

    app.weather:
        class: AppBundle\Weather\Weather
        arguments:
            - '@csa_guzzle.client.weather'
            - '@jms_serializer'
            - %weather_api_key%
